### ISSUE TITLE
Debug file embedded in final NuGet packages

### ISSUE THREAD

**Issue by ggirard07** [MvvmCross/MvvmCross-iOSSupport#13]
Looks like MvvmCross.iOS.Support.nuspec is embedding some temporary *.cs files in the final package currently distributed on NuGet. The package contains the `lib\Xamarin.iOS10\obj` with 3 `TemporaryGeneratedFile_*.cs` file in each Debug and Release.

The problem seems to come from [this line of code](https://github.com/MvvmCross/MvvmCross-iOSSupport/blob/d2d85f7c62fc8db7da9f9c8b24186cdfbf08bfd5/nuspec/MvvmCross.iOS.Support.nuspec#L28) but I am not filling confident to PR on this as I currently do not understand why it is there in the first place (no nuget background, sorry).

**Comment by martijn00** [comment]
I can't reproduce this in the latest version of the repo. Can you check again next release, and reopen if still applicable.
