### ISSUE TITLE
CSProj file errors

### ISSUE THREAD

**Issue by munkii** [MvvmCross/MvvmCross-iOSSupport#21]
I downloaded the MvvmCross-iOSSupport repro to have a look at the new stuff. There are a couple of small issues with the CSPROJ

The MvvmCross.iOS.Support project has a SidePanels folder.
1. The IMvxToggleMenu.cs is in the CsProj files but not on disk. I assume it is old
2. The File IMvbxSideMenu.cs is in source download but not included in the CSPROJ

**Comment by martijn00** [comment]
Fixed in https://github.com/MvvmCross/MvvmCross-iOSSupport/pull/22
