### ISSUE TITLE
JASidePanels vs XamarinSideBar

### ISSUE THREAD

**Issue by IlSocio** [MvvmCross/MvvmCross-iOSSupport#25]
I'm wondering which are the differences between these two components...
Becase I'm not sure about which one I should choose for a project of mine.

This is my basic understanding:
- the JASidePanels component is distribuited by Xamarin
  https://components.xamarin.com/view/jasidepanels
  which is just a binding library around the native library:
  https://github.com/gotosleep/JASidePanels 
  Both the native version and the Binding Library of JASidePanels component don't get new updates since long time.
- the XamarinSideBar is a c# component and can be found here:
  https://github.com/jdehlin/Xamarin-Sidebar
  And seems to receive some contribution once in a while.

Are these statement correct? 
Moreover, do exists any relevant differences in the features provided by these components?

**Comment by martijn00** [comment]
Your statement is correct. And both have mostly the same features, but they have a different look and feel. It is up to your personal preference to pick one of them.

**Comment by IlSocio** [comment]
Some further info and comparison:
http://www.marcbruins.nl/xamarin-ios-hamburger-menu-mvvmcross/
