### ISSUE TITLE
Allow user to use own hamburger icon

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross-iOSSupport#32]
https://github.com/MvvmCross/MvvmCross-iOSSupport/blob/master/MvvmCross.iOS.Support.XamarinSidebar/Hints/MvxSidebarActivePanelPresentationHint.cs#L49

This needs to be configurable

**Comment by Cheesebaron** [comment]
There is currently a bug where assets and resources in libraries do not get included when built on Windows, which MvvmCross is. See https://github.com/Cheesebaron/Chafu/issues/1

**Comment by jamsoft** [comment]
Will have a look at this today as it's something I've wanted in the past too.  I guess to get around this issue for now we could allow the consumer to pass in an instance of a UIImage.
