### ISSUE TITLE
Create Demo Using MvxExpandableTableViewSource 

### ISSUE THREAD

**Issue by jamsoft** [MvvmCross/MvvmCross-iOSSupport#34]
Currently the sample applications do not make use of the MvxExpandableTableViewSource in order to demonstrate its use and functionality.  This should be added in a future version of the library.

**Comment by b099l3** [comment]
I created a sample in this PR in the samples repo https://github.com/MvvmCross/MvvmCross-Samples/pull/53 but I had to slightly modify MvxExpandableTableViewSource. 

I think it would be best if I added my changes to MvxExpandableTableViewSource in this repo #35 then in the samples repo have the demo with the updated iOSSupport. Or have samples in both?

**Comment by jamsoft** [comment]
Probably would be good to have all the samples for the iOSSupport library within it's repo.

**Comment by b099l3** [comment]
Cool I have an example ready, i'll add it here.

**Comment by b099l3** [comment]
Added my sample to #35
