### ISSUE TITLE
Tapping on menu items on Right side bar is not working

### ISSUE THREAD

**Issue by PrasadKurdiMatta** [MvvmCross/MvvmCross-iOSSupport#37]
### Steps to reproduce
1. Download sample app from https://github.com/MarcBruins/MvvmCross-Sidebar-Sample which uses the libraries
2. On Menu view make panel to Right side
3. Launch the app and swipe from right
4. Tap on menu item
5. Not able tap.
### Expected behavior

Able to Tap on right side bar menu items
### Actual behavior

Not able to tap on right side bar menu items
### Configuration

**Platform:** iOS

Info on issue:
Seems be in class MvxSidebarPanelController and if interchange right and left side bar, i can able to tap.

LeftSidebarController = new SidebarController(_subRootViewController, NavigationController, initialEmptySideMenu);
RightSidebarController = new SidebarController(this, _subRootViewController, initialEmptySideMenu);

**Comment by mvanbeusekom** [comment]
@PrasadKurdiMatta have you already tried with the source from MvvmCross repository (instead of the project from Marc Bruins).

Using the MvvmCross version of MvvmCross-iOSSupport (https://github.com/MvvmCross/MvvmCross-iOSSupport) I cannot reproduce the problem.

**Comment by Cheesebaron** [comment]
Looking at @MarcBruins sample, it seems like it is not using the latest version of the library. When filing bugs against MvvmCross, please ensure you are running latest version.

**Comment by PrasadKurdiMatta** [comment]
I did update the nuget in the sample app to latest code and issue still exist.

**Comment by Cheesebaron** [comment]
I can't reproduce in the sample @mvanbeusekom links to.

I've added a TableView on both sides, both accept touches fine. Must be something with @MarcBruins sample that does not work correctly.

**Comment by PrasadKurdiMatta** [comment]
Yes it works fine when we use Hamburger button to bring the fly out menu, but when we swipe from the right the tap doesn't work on menu items.

**Comment by Cheesebaron** [comment]
I tried both and both approaches work fine. Can't reproduce.

**Comment by MarcBruins** [comment]
Will inspect my code and see what's wrong
