### ISSUE TITLE
"Hamburger" icon disappears

### ISSUE THREAD

**Issue by mrtnkrstn** [MvvmCross/MvvmCross-iOSSupport#40]
Can be reproduced in current MvvmCross-iOSSupport.Samples (commit c56c97f).
### Steps to reproduce
1. Run MvvmCross-iOSSupport.Samples with MvvmCross.iOS.Support.Sidebar as startup project
2. Tap on Hamburger icon, notice that sidebar opens and Hamburger icon remains visible
3. Tap on **Example Menu Item** in sidebar, notice that Hamburger icon disappears
### Expected behavior

Hamburger icon should always be visible
### Actual behavior

Hamburger icon disappears after tapping on first menu element
### Configuration

**Version:** 4.2.3

**Platform:** iOS

NOTE: calling ShowMenu for every newly-opened screen does make the Hamburger icon reappear, but it isn't a viable solution because it creates a new instance of the menu

**Comment by martijn00** [comment]
@mvanbeusekom is this a side-effect from your PR?

**Comment by mvanbeusekom** [comment]
@martijn00, @mrtnkrstn, this is by design. The idea is to explicitly set if (and which) menu should be shown per view. 

An example can be found in the "CenterPanelViewModel" which (in the ctor) explicitly loads a left and right menu for this page.

If you want the same menu on all pages you could simply implement this in a base class.

**Comment by jamsoft** [comment]
Indeed, this is by design.

**Comment by mrtnkrstn** [comment]
It is by design to have the Hamburger icon disappear?

**Comment by mvanbeusekom** [comment]
@mrtnkrstn Depends on your perspective. My design requirement was to be able to explicitly indicate if you want to have a menu for the view or not and to be able to show a completely different menu for certain pages (think about a context based menu on the right side of the app showing option depending on the content shown). 

There will always be different ways to look at it. In my previous reply I offered a possible solution, of course there are more (e.g. utilising dependency injection). Or if you really want a different approach you are more then welcome to fork the code and make a custom implementation.

**Comment by mrtnkrstn** [comment]
@mvanbeusekom the problem is that every time you call `ShowViewModel<MenuViewModel>()`, a new instance of both the MenuViewModel and the Menu is instantiated. Any advice on how to keep the icon _until_ `ShowViewModel()` is called again (if at all)? So, basically call `ShowViewModel()` only once to instantiate the menu, and then every Menu Page has the Hamburger icon.

**Comment by mrtnkrstn** [comment]
Any advice/pointers would be appreciated!

**Comment by mvanbeusekom** [comment]
I am away for holiday at the moment and will be back around 13th of October. When back (and if time permits) I will look into it and make an version which caches and reuses the menu.

If you can't wait, the way I am thinking is making a few small modifications in the `Show(IMvxIosView)` method of the `MvxSidebarPresenter` class which is responsible of loading the correct view.
