### ISSUE TITLE
MvxExpandableTableViewSource: GetViewForHeader multiple buttons added

### ISSUE THREAD

**Issue by chrislamont** [MvvmCross/MvvmCross-iOSSupport#47]
In the `MvxExpandableTableViewSource`:
[link](https://github.com/MvvmCross/MvvmCross-iOSSupport/blob/master/MvvmCross.iOS.Support/Views/MvxExpandableTableViewSource.cs)

In the `GetViewForHeader` method, there is a new button added to the header every time the method is called. 

As the header is obtained through the `GetOrCreateHeaderCellFor` method, the cell may have already been created and is being reused. Therefore you will have multiple buttons added to the same `header`, all calling the `EventHandler` method with different `section`'s.

**Comment by b099l3** [comment]
I have created pull request #55 to fix this issue.

It adds the hidden header button only if it hasnt been already. If it has been added it changes the tag on the button to current section, which is uses in its event handler.
