### ISSUE TITLE
MvxSidePanelsPresenter bug - IOS

### ISSUE THREAD

**Issue by flaviusdemian** [MvvmCross/MvvmCross-iOSSupport#48]
I am using the latest Xamarin version and MvvmCross 4.3.0 

The problems occurs when I navigate from screen to screen randomly. Let's say I have an home screen and from there I go to UIViewController A then I go back to Home, then I go to UIViewController B and then back to home again, then I go to UIViewController A again and then back to home again, after I go to B again it sometimes breaks...

As an actual behavior it somehow mixed the view models and because the outlets are not there it just breaks and crashes.
### Configuration

**Version:** 4.3

**Platform:** iOS

Stacktrace:

Unable to cast object of type 'GoWorky.Mobile.iOS.Employer.ChooseManagerViewController' (Objective-C type: 'ChooseLocationViewController') to type 'GoWorky.Mobile.iOS.Employer.ChooseLocationViewController'.
Additional information:
	Selector: setTableView:
	Method: GoWorky.Mobile.iOS.Employer.ChooseLocationViewController:set_TableView (UIKit.UITableView)

_________

  at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/3859/b638977c/source/xamarin-macios/src/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/3859/b638977c/source/xamarin-macios/src/UIKit/UIApplication.cs:63 
  at GoWorky.Mobile.iOS.Employer.Application.Main (System.String[] args) [0x00009] in /Users/flaviusdemian/projects/UpWorky/UpWorky.Mobile/GoWorky.Mobile.iOS.Employer/Main.cs:14 
The idea is that it has a confusion with the previous view controller I was besides Home - at some point it swaps UIViewController A with UIViewController B.

[Archive.zip](https://github.com/MvvmCross/MvvmCross-iOSSupport/files/562879/Archive.zip)

I can provide more data if needed.

Here you have the mvx trace:

mvx: Diagnostic: 114.11 Showing ViewModel ChooseLocationViewModel
iOSNavigation: Diagnostic: 114.11 Navigate requested
mvx: Warning: 114.13 Hint ignored MvxActivePanelPresentationHint
mvx: Diagnostic: 115.76 Requesting presentation change
mvx: Warning: 115.76 Hint ignored MvxClosePresentationHint
mvx: Diagnostic: 117.18 Showing ViewModel ChooseLocationViewModel
iOSNavigation: Diagnostic: 117.18 Navigate requested
mvx: Warning: 117.19 Hint ignored MvxActivePanelPresentationHint
mvx: Diagnostic: 118.18 Showing ViewModel AddLocationDialogViewModel
iOSNavigation: Diagnostic: 118.18 Navigate requested
mvx: Warning: 118.20 Hint ignored MvxActivePanelPresentationHint
mvx: Diagnostic: 122.92 Showing ViewModel ChooseManagerViewModel
iOSNavigation: Diagnostic: 122.92 Navigate requested
mvx: Warning: 122.93 Hint ignored MvxActivePanelPresentationHint
mvx: Diagnostic: 124.63 Requesting presentation change
mvx: Warning: 124.63 Hint ignored MvxClosePresentationHint
mvx: Diagnostic: 126.03 Showing ViewModel ChooseManagerViewModel
iOSNavigation: Diagnostic: 126.03 Navigate requested
mvx: Warning: 126.04 Hint ignored MvxActivePanelPresentationHint
mvx: Diagnostic: 127.08 Showing ViewModel AddManagerDialogViewModel
iOSNavigation: Diagnostic: 127.08 Navigate requested
mvx: Warning: 127.10 Hint ignored MvxActivePanelPresentationHint
Thread finished: <Thread Pool> #11
Thread started: <Thread Pool> #20
mvx: Diagnostic: 130.85 Showing ViewModel ChooseLocationViewModel
iOSNavigation: Diagnostic: 130.85 Navigate requested
mvx: Warning: 130.86 Hint ignored MvxActivePanelPresentationHint
[Archive.zip](https://github.com/MvvmCross/MvvmCross-iOSSupport/files/562891/Archive.zip)

**Comment by Cheesebaron** [comment]
Providing a reproducible sample would be a great help.
