### ISSUE TITLE
MvxSidePanels JASidePanel bug

### ISSUE THREAD

**Issue by flaviusdemian** [MvvmCross/MvvmCross-iOSSupport#53]
https://github.com/MvvmCross/MvvmCross-iOSSupport/issues/53> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools
I have the latest stable:

Apple Developer Tools
Xcode 8.1 (11544)
Build 8B62

Xamarin.iOS
Version: 10.2.0.4 (Xamarin Studio Community)
Hash: b638977
Branch: xcode8.1
Build date: 2016-10-25 14:38:48-0400

### Steps to reproduce

1. I just start the application and show the home view mode which has also a menu in the left part.

### Expected behavior
It should not thrown any navigation exception because when it is broken the NavigationViewController stack is not working properly!

### Configuration

**Version:** 4.4

**Platform:** iOS

Stack Trace:

2016-11-06 20:36:41.774 Xamarin.iOS: Received unhandled ObjectiveC exception: NSInternalInconsistencyException <MvxMultiPanelController: 0x1381cbda0>: An -observeValueForKeyPath:ofObject:change:context: message was received but not handled.
Key path: view
Observed object: <UINavigationController: 0x1379be400>
Change: {
    kind = 1;
}
Context: 0x105e9a4d0
----------------------------------------------------------------------------------
Exception is: Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: <Common_MvxMultiPanelController: 0x1381cbda0>: An -observeValueForKeyPath:ofObject:change:context: message was received but not handled.
Key path: view
Observed object: <UINavigationController: 0x1379be400>
Change: {
    kind = 1;
}
Context: 0x105e9a4d0
Native stack trace:
	0   CoreFoundation                      0x0000000180bd2dc8 <redacted> + 148
	1   libobjc.A.dylib                     0x0000000180237f80 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000180bd2cf8 <redacted> + 0
	3   Foundation                          0x0000000181578ac0 <redacted> + 164
	4   0x0000000100100950 -[JASidePanelController observeValueForKeyPath:ofObject:change:context:] + 132
	5   Foundation                          0x00000001814cff64 <redacted> + 304
	6   Foundation                          0x00000001814e99fc <redacted> + 220
	7   Foundation                          0x00000001814e97bc <redacted> + 124
	8   libJASidePanels.dll.dylib           0x0000000105e83804 -[JASidePanelController setCenterPanel:] + 248
	9   libJASidePanels.dll.dylib           0x0000000105e93308 wrapper_managed_to_native_ApiDefinition_Messaging_void_objc_msgSendSuper_IntPtr_intptr_intptr_intptr + 216
	10  libJASidePanels.dll.dylib           0x0000000105e8d564 JASidePanels_JASidePanelController_set_CenterPanel_UIKit_UIViewController + 612
	11  dylib 0x00000001058a8ec0 _Common_CustomMvxSidePanelsPresenter_ShowFirstView_UIKit_UIViewController + 544
	12  dylib 0x00000001058a69d8 Common_CustomMvxSidePanelsPresenter_Show_MvvmCross_iOS_Views_IMvxIosView + 1336
	13  libMvvmCross.iOS.dll.dylib          0x000000010550d9fc MvvmCross_iOS_Views_Presenters_MvxIosViewPresenter_Show_MvvmCross_Core_ViewModels_MvxViewModelRequest + 204
	14  libMvvmCross.iOS.dll.dylib          0x00000001055122a4 MvvmCross_iOS_Views_MvxIosViewDispatcher__c__DisplayClass2_0__ShowViewModelb__0 + 276
	15  libMvvmCross.iOS.dll.dylib          0x00000001055069f0 MvvmCross_iOS_Views_MvxIosUIThreadDispatcher_RequestMainThreadAction_System_Action + 288
	16  libMvvmCross.iOS.dll.dylib          0x000000010550658c MvvmCross_iOS_Views_MvxIosViewDispatcher_ShowViewModel_MvvmCross_Core_ViewModels_MvxViewModelRequest + 380
	17  libGoWorky.Mobile.iOS.Common.dll.dylib 0x000000010589c388 GoWorky_Mobile_iOS_Common_Services_NavigationService_ShowViewModelFromOutsideOfMvvmCross_T_REF_System_Collections_Generic_IDictionary_2_string_string + 408
	18  libGoWorky.Mobile.iOS.Employer.exe.dylib 0x000000010073baf0 GoWorky_Mobile_iOS_Employer_AppDelegate_FinishedLaunching_UIKit_UIApplication_Foundation_NSDictionary + 1712
	19  libmscorlib.dll.dylib               0x0000000100e7d534 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 244
	20  libmonosgen-2.0.dylib               0x00000001004021dc mono_jit_runtime_invoke + 1772
	21  libmonosgen-2.0.dylib               0x0000000100472d0c do_runtime_invoke + 112
	22  libmonosgen-2.0.dylib               0x0000000100472c68 mono_runtime_invoke + 208
	23  GoWorky.Mobile.iOS.Employer         0x000000010018fd54 _ZL31native_to_managed_trampoline_48P11objc_objectP13objc_selectorPP11_MonoMethodP13UIApplicationP12NSDictionaryPKcSB_SB_SB_ + 692
	24  GoWorky.Mobile.iOS.Employer         0x000000010018fa90 -[AppDelegate application:didFinishLaunchingWithOptions:] + 96
	25  UIKit                               0x0000000185daa9c0 <redacted> + 400
	26  UIKit                               0x0000000185fda184 <redacted> + 2904
	27  UIKit                               0x0000000185fde5f0 <redacted> + 1684
	28  UIKit                               0x0000000185fdb764 <redacted> + 168
	29  FrontBoardServices                  0x00000001825737ac <redacted> + 36
	30  FrontBoardServices                  0x0000000182573618 <redacted> + 168
	31  FrontBoardServices                  0x00000001825739c8 <redacted> + 56
	32  CoreFoundation                      0x0000000180b8909c <redacted> + 24
	33  CoreFoundation                      0x0000000180b88b30 <redacted> + 540
	34  CoreFoundation                      0x0000000180b86830 <redacted> + 724
	35  CoreFoundation                      0x0000000180ab0c50 CFRunLoopRunSpecific + 384
	36  UIKit                               0x0000000185da394c <redacted> + 460
	37  UIKit                               0x0000000185d9e088 UIApplicationMain + 204
	38  libXamarin.iOS.dll.dylib            0x00000001009d24f4 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 324
	39  libXamarin.iOS.dll.dylib            0x000000010096057c UIKit_UIApplication_Main_string___intptr_intptr + 44
	40  libXamarin.iOS.dll.dylib            0x000000010096053c UIKit_UIApplication_Main_string___string_string + 172
	41  libGoWorky.Mobile.iOS.Employer.exe.dylib 0x000000010073b094 GoWorky_Mobile_iOS_Employer_Application_Main_string__ + 196
	42  libmscorlib.dll.dylib               0x0000000100e7d534 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 244
	43  libmonosgen-2.0.dylib               0x00000001004021dc mono_jit_runtime_invoke + 1772
	44  libmonosgen-2.0.dylib               0x0000000100472d0c do_runtime_invoke + 112
	45  libmonosgen-2.0.dylib               0x00000001004752f0 mono_runtime_exec_main + 832
	46  libmonosgen-2.0.dylib               0x0000000100474f0c mono_runtime_run_main + 764
	47  libmonosgen-2.0.dylib               0x00000001003e67f8 mono_jit_exec + 236
	48  libxamarin-debug.dylib              0x00000001006ddcd8 xamarin_main + 2168
	49  GoWorky.Mobile.iOS.Employer         0x00000001001a986c main + 96
	50  libdyld.dylib                       0x000000018064e8b8 <redacted> + 4

  at (wrapper managed-to-native) ApiDefinition.Messaging:void_objc_msgSendSuper_IntPtr (intptr,intptr,intptr)
  at JASidePanels.JASidePanelController.set_CenterPanel (UIKit.UIViewController value) [0x00061] in <1ac433a8189e442a9703ae131fdc616e>:0 
  at GoWorky.Mobile.iOS.Common.CustomMvxSidePanelsPresenter.ShowFirstView (UIKit.UIViewController viewController) [0x00033] in /Users/flaviusdemian/projects/UpWorky/UpWorky.Mobile/GoWorky.Mobile.iOS.Common/UI/Presenter/CustomMvxSidePanelsPresenter.cs:562 	0   CoreFoundation                      0x0000000180bd2dc8 <redacted> + 148
	1   libobjc.A.dylib                     0x0000000180237f80 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000180bd2cf8 <redacted> + 0
	3   Foundation                          0x0000000181578ac0 <redacted> + 164
	4   GoWorky.Mobile.iOS.Employer         0x0000000100100950 -[JASidePanelController observeValueForKeyPath:ofObject:change:context:] + 132
	5   Foundation                          0x00000001814cff64 <redacted> + 304
	6   Foundation                          0x00000001814e99fc <redacted> + 220
	7   Foundation                          0x00000001814e97bc <redacted> + 124
	8   libJASidePanels.dll.dylib           0x0000000105e83804 -[JASidePanelController setCenterPanel:] + 248
	9   libJASidePanels.dll.dylib           0x0000000105e93308 wrapper_managed_to_native_ApiDefinition_Messaging_void_objc_msgSendSuper_IntPtr_intptr_intptr_intptr + 216
	10  libJASidePanels.dll.dylib           0x0000000105e8d564 JASidePanels_JASidePanelController_set_CenterPanel_UIKit_UIViewController + 612
	11  libGoWorky.Mobile.iOS.Common.dll.dylib 0x00000001058a8ec0 GoWorky_Mobile_iOS_Common_CustomMvxSidePanelsPresenter_ShowFirstView_UIKit_UIViewController + 544
	12  libGoWorky.Mobile.iOS.Common.dll.dylib 0x00000001058a69d8 GoWorky_Mobile_iOS_Common_CustomMvxSidePanelsPresenter_Show_MvvmCross_iOS_Views_IMvxIosView + 1336
	13  libMvvmCross.iOS.dll.dylib          0x000000010550d9fc MvvmCross_iOS_Views_Presenters_MvxIosViewPresenter_Show_MvvmCross_Core_ViewModels_MvxViewModelRequest + 204
	14  libMvvmCross.iOS.dll.dylib          0x00000001055122a4 MvvmCross_iOS_Views_MvxIosViewDispatcher__c__DisplayClass2_0__ShowViewModelb__0 + 276
	15  libMvvmCross.iOS.dll.dylib          0x00000001055069f0 MvvmCross_iOS_Views_MvxIosUIThreadDispatcher_RequestMainThreadAction_System_Action + 288
	16  libMvvmCross.iOS.dll.dylib          0x000000010550658c MvvmCross_iOS_Views_MvxIosViewDispatcher_ShowViewModel_MvvmCross_Core_ViewModels_MvxViewModelRequest + 380
	17  libGoWorky.Mobile.iOS.Common.dll.dylib 0x000000010589c388 GoWorky_Mobile_iOS_Common_Services_NavigationService_ShowViewModelFromOutsideOfMvvmCross_T_REF_System_Collections_Generic_IDictionary_2_string_string + 408
	18  libGoWorky.Mobile.iOS.Employer.exe.dylib 0x000000010073baf0 GoWorky_Mobile_iOS_Employer_AppDelegate_FinishedLaunching_UIKit_UIApplication_Foundation_NSDictionary + 1712
	19  libmscorlib.dll.dylib               0x0000000100e7d534 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 244
	20  libmonosgen-2.0.dylib               0x00000001004021dc mono_jit_runtime_invoke + 1772
	21  libmonosgen-2.0.dylib               0x0000000100472d0c do_runtime_invoke + 112
	22  libmonosgen-2.0.dylib               0x0000000100472c68 mono_runtime_invoke + 208
	23  GoWorky.Mobile.iOS.Employer         0x000000010018fd54 _ZL31native_to_managed_trampoline_48P11objc_objectP13objc_selectorPP11_MonoMethodP13UIApplicationP12NSDictionaryPKcSB_SB_SB_ + 692
	24  GoWorky.Mobile.iOS.Employer         0x000000010018fa90 -[AppDelegate application:didFinishLaunchingWithOptions:] + 96
	25  UIKit                               0x0000000185daa9c0 <redacted> + 400
	26  UIKit                               0x0000000185fda184 <redacted> + 2904
	27  UIKit                               0x0000000185fde5f0 <redacted> + 1684
	28  UIKit                               0x0000000185fdb764 <redacted> + 168
	29  FrontBoardServices                  0x00000001825737ac <redacted> + 36
	30  FrontBoardServices                  0x0000000182573618 <redacted> + 168
	31  FrontBoardServices                  0x00000001825739c8 <redacted> + 56
	32  CoreFoundation                      0x0000000180b8909c <redacted> + 24
	33  CoreFoundation                      0x0000000180b88b30 <redacted> + 540
	34  CoreFoundation                      0x0000000180b86830 <redacted> + 724
	35  CoreFoundation                      0x0000000180ab0c50 CFRunLoopRunSpecific + 384
	36  UIKit                               0x0000000185da394c <redacted> + 460
	37  UIKit                               0x0000000185d9e088 UIApplicationMain + 204
	38  libXamarin.iOS.dll.dylib            0x00000001009d24f4 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 324
	39  libXamarin.iOS.dll.dylib            0x000000010096057c UIKit_UIApplication_Main_string___intptr_intptr + 44
	40  libXamarin.iOS.dll.dylib            0x000000010096053c UIKit_UIApplication_Main_string___string_string + 172
	41  libGoWorky.Mobile.iOS.Employer.exe.dylib 0x000000010073b094 GoWorky_Mobile_iOS_Employer_Application_Main_string__ + 196
	42  libmscorlib.dll.dylib               0x0000000100e7d534 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 244
	43  libmonosgen-2.0.dylib               0x00000001004021dc mono_jit_runtime_invoke + 1772
	44  libmonosgen-2.0.dylib               0x0000000100472d0c do_runtime_invoke + 112
	45  libmonosgen-2.0.dylib               0x00000001004752f0 mono_runtime_exec_main + 832
	46  libmonosgen-2.0.dylib               0x0000000100474f0c mono_runtime_run_main + 764
	47  libmonosgen-2.0.dylib               0x00000001003e67f8 mono_jit_exec + 236
	48  libxamarin-debug.dylib              0x00000001006ddcd8 xamarin_main + 2168
	49  GoWorky.Mobile.iOS.Employer         0x00000001001a986c main + 96
	50  libdyld.dylib                       0x000000018064e8b8 <redacted> + 4

----------------------------------------------------------------------------------

2016-11-06 20:36:41.878 GoWorky.Mobile.iOS.Employer[506:128384] mvx: Diagnostic:   8.72 Showing ViewModel MenuViewModel
2016-11-06 20:36:41.878 GoWorky.Mobile.iOS.Employer[506:128384] iOSNavigation: Diagnostic:   8.72 Navigate requested

**Comment by mvanbeusekom** [comment]
Unfortunately I am failing to reproduce the problem in the sample application. Here are the steps I took:
1. Added the "MvvmCross.iOS.Support.JASidePanelsSample.iOS.csproj" sample project to the solution (will make a PR to make sure it is included by default);
2. Compiled and run the sample project;
3. On the first page "Center Panel" op the menu;
4. Click on of the buttons in the menu;
5. The appropriate page opens;
6. Repeat from step 4.

I don't get an exception not matter where I click or try to navigate too. Can you maybe provide a sample?

**Comment by flaviusdemian** [comment]
Hello Maurits,

We solved it together on skype if you recall. 
This is the PR:
https://github.com/MvvmCross/MvvmCross-iOSSupport/pull/54

Best regards,

Flavius
