### ISSUE TITLE
MvvmCross Ios Navigation bug

### ISSUE THREAD

**Issue by flaviusdemian** [MvvmCross/MvvmCross-iOSSupport#66]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

https://github.com/slown1/IosNavigationBug

>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools
I am on the stable channel and I am up to date.

### Steps to reproduce

After you login go from the menu to the Notifications, then Shift Templates, then History and repeat these steps until it breaks. 
The exception is caught in

You can run the application in the simulator with the Developer Automatic settings.
I have noticed that in the simulator it reproduces harder and it also has another crash which seems like a leek. Can you also help here?

1. http://www.screencast.com/t/3tZnZIvXDAf

### Expected behavior
It should not crash

### Actual behavior
It crashes with exceptions which are like this:

Unable to cast object of type 'GoWorky.Mobile.iOS.Employer.TalentPoolViewController' (Objective-C type: 'NotificationsViewController') to type 'GoWorky.Mobile.iOS.Employer.NotificationsViewController'.
Additional information:
	Selector: setTableView:
	Method: GoWorky.Mobile.iOS.Employer.NotificationsViewController:set_TableView (UIKit.UITableView)

Unable to cast object of type 'GoWorky.Mobile.iOS.Employer.TemplatesViewController' (Objective-C type: 'TalentPoolViewController') to type 'GoWorky.Mobile.iOS.Employer.TalentPoolViewController'.
Additional information:
	Selector: setTableView:
	Method: GoWorky.Mobile.iOS.Employer.TalentPoolViewController:set_TableView (UIKit.UITableView)

### Configuration

**Version:** 4.4.0
 

**Platform:** iOS

**Comment by flaviusdemian** [comment]
Any ideas guys? I am running out of time.

**Comment by Cheesebaron** [comment]
Most of the time when I launch the app in the sim it just shows the backdrop with the top of a head.

When it "works" and I do the steps you provide the app just crashes without any unhandled exceptions without a useful stack trace. I guess the exception is swallowed by some try/catch where you don't handle the exception and don't rethrow it.

I appreciate a reproducible sample. But what is meant by that is a small narrowed down sample and not a full solution where loads of crazy things are going. Think more a minimum viable repro sample.

I can't debug this.

**Comment by flaviusdemian** [comment]
I will remove all the try catch block immediately and provide a smaller sample

**Comment by flaviusdemian** [comment]
I have pushes trimmed as much as I could from the code. My presenter is the default one from the Xamarin Sidebar Sample, meaning: MvxSidebarPresenter.

I have added another screen recording with the device and with the simulator. It seems that on the simulator the swap between the viewcontrollers happens rare.

http://www.screencast.com/t/vXDEPvknDEqG
[StackTraceSimulator.txt](https://github.com/MvvmCross/MvvmCross-iOSSupport/files/614382/StackTraceSimulator.txt)
